@startuml GatewayModel

hide empty members

class "Citizen" as citizen
class "Condition" as condition
class "Goal" as goal
class "Citizens Own Observation" as citizensOwnObservation
class "Planned Intervention" as carePlannedIntervention
class "Encounter" as encounter
class "Follow Up Observation" as careFollowUpObservation
class "Matter of Interest Observation" as matterOfInterestObservation
' class "Matter of Interest Severity" as matterOfInterestSeverityObservation

citizen --"*" condition
citizen --"*" matterOfInterestObservation
citizen --"*" carePlannedIntervention

condition --"0..1" goal
condition --"0..2" citizensOwnObservation

matterOfInterestObservation --"0..2" citizensOwnObservation

condition --"0..1" encounter

carePlannedIntervention -"*" condition

carePlannedIntervention -"0..1" encounter

' encounter -"0..1" careFollowUpObservation

matterOfInterestObservation --"0..1" encounter
' matterOfInterestObservation --"0..1" matterOfInterestSeverityObservation

carePlannedIntervention --"0..1" careFollowUpObservation
condition --"0..1" careFollowUpObservation
' matterOfInterestObservation --"0..1" careFollowUpObservation

@enduml